- name: Run show clock
  hosts: R1
  gather_facts: false

  tasks:
    - name: run raw commands
      raw: show clock
      
    - name: print the time
debug: msg="The date and time of {{ inventory_hostname }} is {{ show_clock.stdout }}"
